/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Janelas;

/**
 *
 * @author luiz.marchiori
 */
public class adicionarPizza extends javax.swing.JFrame {

    /**
     * Creates new form adicionarPizza
     */
    public adicionarPizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labNomePizza = new javax.swing.JLabel();
        txtNomePizza = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chkQueijo = new javax.swing.JCheckBox();
        chkCalabresa = new javax.swing.JCheckBox();
        chkPresunto = new javax.swing.JCheckBox();
        chkFileMignon = new javax.swing.JCheckBox();
        chkFrango = new javax.swing.JCheckBox();
        chKCostelinha = new javax.swing.JCheckBox();
        chkBacon = new javax.swing.JCheckBox();
        chkOvo = new javax.swing.JCheckBox();
        chkLombo = new javax.swing.JCheckBox();
        ChkPeitoDePeru = new javax.swing.JCheckBox();
        chkProvolone = new javax.swing.JCheckBox();
        chkCatupiry = new javax.swing.JCheckBox();
        chkCheddar = new javax.swing.JCheckBox();
        chkCreamCheese = new javax.swing.JCheckBox();
        chkGorgonzola = new javax.swing.JCheckBox();
        chkParmesao = new javax.swing.JCheckBox();
        chkCebola = new javax.swing.JCheckBox();
        chkChampignon = new javax.swing.JCheckBox();
        chkAlho = new javax.swing.JCheckBox();
        chkMilho = new javax.swing.JCheckBox();
        chkPalmito = new javax.swing.JCheckBox();
        chkMolhoPesto = new javax.swing.JCheckBox();
        chkDoritos = new javax.swing.JCheckBox();
        chkCarne = new javax.swing.JCheckBox();
        botConfirmar = new javax.swing.JButton();
        botCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Criar Pizza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        labNomePizza.setText("Nome da Pizza");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Ingredientes");

        chkQueijo.setBackground(new java.awt.Color(255, 255, 255));
        chkQueijo.setText("Queijo mussarela");

        chkCalabresa.setBackground(new java.awt.Color(255, 255, 255));
        chkCalabresa.setText("Calabresa");

        chkPresunto.setBackground(new java.awt.Color(255, 255, 255));
        chkPresunto.setText("Presunto");

        chkFileMignon.setBackground(new java.awt.Color(255, 255, 255));
        chkFileMignon.setText("Filé mignon em cubos");
        chkFileMignon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFileMignonActionPerformed(evt);
            }
        });

        chkFrango.setBackground(new java.awt.Color(255, 255, 255));
        chkFrango.setText("Frango desfiado");

        chKCostelinha.setBackground(new java.awt.Color(255, 255, 255));
        chKCostelinha.setText("Costelinha desfiada");

        chkBacon.setBackground(new java.awt.Color(255, 255, 255));
        chkBacon.setText("Bacon artesanal em lascas");

        chkOvo.setBackground(new java.awt.Color(255, 255, 255));
        chkOvo.setText("Ovo");

        chkLombo.setBackground(new java.awt.Color(255, 255, 255));
        chkLombo.setText("Lombo canadense");

        ChkPeitoDePeru.setBackground(new java.awt.Color(255, 255, 255));
        ChkPeitoDePeru.setText("Peito de peru");

        chkProvolone.setBackground(new java.awt.Color(255, 255, 255));
        chkProvolone.setText("Provolone");

        chkCatupiry.setBackground(new java.awt.Color(255, 255, 255));
        chkCatupiry.setText("Catupiry");

        chkCheddar.setBackground(new java.awt.Color(255, 255, 255));
        chkCheddar.setText("Cheddar");

        chkCreamCheese.setBackground(new java.awt.Color(255, 255, 255));
        chkCreamCheese.setText("Cream Cheese");

        chkGorgonzola.setBackground(new java.awt.Color(255, 255, 255));
        chkGorgonzola.setText("Gorgonzola");

        chkParmesao.setBackground(new java.awt.Color(255, 255, 255));
        chkParmesao.setText("Parmesão Ralado");

        chkCebola.setBackground(new java.awt.Color(255, 255, 255));
        chkCebola.setText("Cebola");

        chkChampignon.setBackground(new java.awt.Color(255, 255, 255));
        chkChampignon.setText("Champignon");

        chkAlho.setBackground(new java.awt.Color(255, 255, 255));
        chkAlho.setText("Alho frito");

        chkMilho.setBackground(new java.awt.Color(255, 255, 255));
        chkMilho.setText("Milho");

        chkPalmito.setBackground(new java.awt.Color(255, 255, 255));
        chkPalmito.setText("Palmito");

        chkMolhoPesto.setBackground(new java.awt.Color(255, 255, 255));
        chkMolhoPesto.setText("Molho pesto");

        chkDoritos.setBackground(new java.awt.Color(255, 255, 255));
        chkDoritos.setText("Doritos");

        chkCarne.setBackground(new java.awt.Color(255, 255, 255));
        chkCarne.setText("Carne moída");

        botConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/botao-adicionar.png"))); // NOI18N
        botConfirmar.setText("Confirmar");

        botCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/sair.png"))); // NOI18N
        botCancelar.setText("Cancelar e voltar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkOvo)
                            .addComponent(chkCatupiry)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkFrango)
                                    .addComponent(chkParmesao)
                                    .addComponent(chkFileMignon)
                                    .addComponent(chkChampignon)
                                    .addComponent(chkMolhoPesto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkAlho)
                                            .addComponent(chkProvolone)
                                            .addComponent(chkCalabresa)
                                            .addComponent(chKCostelinha)
                                            .addComponent(ChkPeitoDePeru)
                                            .addComponent(chkCreamCheese)
                                            .addComponent(chkMilho)
                                            .addComponent(chkDoritos))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkCarne)
                                            .addComponent(chkPalmito)
                                            .addComponent(chkCebola)
                                            .addComponent(chkBacon)
                                            .addComponent(chkLombo)
                                            .addComponent(chkPresunto)
                                            .addComponent(chkCheddar)
                                            .addComponent(chkGorgonzola)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel2))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labNomePizza)
                                    .addComponent(chkQueijo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomePizza, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNomePizza)
                    .addComponent(txtNomePizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkQueijo)
                    .addComponent(chkCalabresa)
                    .addComponent(chkPresunto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkFrango)
                    .addComponent(chKCostelinha)
                    .addComponent(chkLombo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkOvo)
                    .addComponent(ChkPeitoDePeru)
                    .addComponent(chkCheddar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCatupiry)
                    .addComponent(chkCreamCheese)
                    .addComponent(chkGorgonzola))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkParmesao)
                    .addComponent(chkBacon)
                    .addComponent(chkProvolone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkFileMignon)
                    .addComponent(chkCebola)
                    .addComponent(chkAlho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkChampignon)
                    .addComponent(chkMilho)
                    .addComponent(chkPalmito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMolhoPesto)
                    .addComponent(chkDoritos)
                    .addComponent(chkCarne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botConfirmar)
                    .addComponent(botCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkFileMignonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFileMignonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFileMignonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("WindowsXP".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adicionarPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adicionarPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adicionarPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adicionarPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adicionarPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChkPeitoDePeru;
    private javax.swing.JButton botCancelar;
    private javax.swing.JButton botConfirmar;
    private javax.swing.JCheckBox chKCostelinha;
    private javax.swing.JCheckBox chkAlho;
    private javax.swing.JCheckBox chkBacon;
    private javax.swing.JCheckBox chkCalabresa;
    private javax.swing.JCheckBox chkCarne;
    private javax.swing.JCheckBox chkCatupiry;
    private javax.swing.JCheckBox chkCebola;
    private javax.swing.JCheckBox chkChampignon;
    private javax.swing.JCheckBox chkCheddar;
    private javax.swing.JCheckBox chkCreamCheese;
    private javax.swing.JCheckBox chkDoritos;
    private javax.swing.JCheckBox chkFileMignon;
    private javax.swing.JCheckBox chkFrango;
    private javax.swing.JCheckBox chkGorgonzola;
    private javax.swing.JCheckBox chkLombo;
    private javax.swing.JCheckBox chkMilho;
    private javax.swing.JCheckBox chkMolhoPesto;
    private javax.swing.JCheckBox chkOvo;
    private javax.swing.JCheckBox chkPalmito;
    private javax.swing.JCheckBox chkParmesao;
    private javax.swing.JCheckBox chkPresunto;
    private javax.swing.JCheckBox chkProvolone;
    private javax.swing.JCheckBox chkQueijo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labNomePizza;
    private javax.swing.JTextField txtNomePizza;
    // End of variables declaration//GEN-END:variables
}
