/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Janelas;

import Controladora.GerenciadorDominio;
import Controladora.Interface_Grafica;
import Dominio.Adicional;
import Dominio.Cliente;
import Dominio.Ingrediente;
import Dominio.Pizza;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;

/**
 *
 * @author luiz.marchiori
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private Interface_Grafica gerIG;
    private Cliente cliSelecionado;
    private double subtotal = 0;
    private int entregar = 0;
    private char tamanho;

    public JanelaPrincipal(Interface_Grafica gerIG) {
        this.gerIG = gerIG;
        this.cliSelecionado = null;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBorda = new javax.swing.ButtonGroup();
        grupoTamanho = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtRua = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        botPesquisar = new javax.swing.JButton();
        botAlterar = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();
        botLimpar = new javax.swing.JButton();
        botAdicionarCliente1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        radioPequena = new javax.swing.JRadioButton();
        radioMedia = new javax.swing.JRadioButton();
        radioGrande = new javax.swing.JRadioButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        bordaPadrao = new javax.swing.JRadioButton();
        radioCheddar = new javax.swing.JRadioButton();
        radioCatupiry = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        botEditarPizza = new javax.swing.JButton();
        cmbPizzas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        chkCebola = new javax.swing.JCheckBox();
        chkMussarela = new javax.swing.JCheckBox();
        chkPalmito = new javax.swing.JCheckBox();
        chkBacon = new javax.swing.JCheckBox();
        chkAzeitona = new javax.swing.JCheckBox();
        chkOregano = new javax.swing.JCheckBox();
        chkPresunto = new javax.swing.JCheckBox();
        chkLombo = new javax.swing.JCheckBox();
        chkAlho = new javax.swing.JCheckBox();
        chkAtum = new javax.swing.JCheckBox();
        chkOvo = new javax.swing.JCheckBox();
        chkBarbecue = new javax.swing.JCheckBox();
        chkMaionese = new javax.swing.JCheckBox();
        botAdicionar = new javax.swing.JButton();
        botEncerrar = new javax.swing.JButton();
        botSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCarrinho = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criar Pedido");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setText("Nome");
        jPanel3.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 114, -1, -1));

        lblBairro.setText("Bairro");
        jPanel3.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 145, -1, -1));

        lblRua.setText("Rua");
        jPanel3.add(lblRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 176, -1, -1));

        lblNumero.setText("Número");
        jPanel3.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 207, -1, -1));

        lblTelefone.setText("Telefone");
        jPanel3.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 238, -1, -1));

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 235, 228, -1));
        jPanel3.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 173, 228, -1));
        jPanel3.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 142, 228, -1));
        jPanel3.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 111, 228, -1));

        botPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/lupa.png"))); // NOI18N
        botPesquisar.setText("Pesquisar");
        botPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesquisarActionPerformed(evt);
            }
        });
        jPanel3.add(botPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 136, -1));

        botAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/conjunto-de-setas-de-sincronizacao.png"))); // NOI18N
        botAlterar.setText("Alterar");
        botAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAlterarActionPerformed(evt);
            }
        });
        jPanel3.add(botAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, 45));

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        jPanel3.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, -1));

        botLimpar.setText("Limpar");
        botLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimparActionPerformed(evt);
            }
        });
        jPanel3.add(botLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 45));

        botAdicionarCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/verifica.png"))); // NOI18N
        botAdicionarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdicionarCliente1ActionPerformed(evt);
            }
        });
        jPanel3.add(botAdicionarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, 45));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tamanho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        radioPequena.setBackground(new java.awt.Color(255, 255, 255));
        grupoTamanho.add(radioPequena);
        radioPequena.setMnemonic('P');
        radioPequena.setSelected(true);
        radioPequena.setText("Pequena");

        radioMedia.setBackground(new java.awt.Color(255, 255, 255));
        grupoTamanho.add(radioMedia);
        radioMedia.setMnemonic('M');
        radioMedia.setText("Média");

        radioGrande.setBackground(new java.awt.Color(255, 255, 255));
        grupoTamanho.add(radioGrande);
        radioGrande.setMnemonic('G');
        radioGrande.setText("Grande");

        jTextField5.setEditable(false);
        jTextField5.setText("+5,00");

        jTextField6.setEditable(false);
        jTextField6.setText("+15,00");

        jTextField7.setEditable(false);
        jTextField7.setText("+20,00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioPequena)
                    .addComponent(radioMedia)
                    .addComponent(radioGrande))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jTextField5)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPequena)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMedia)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioGrande)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bordas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        bordaPadrao.setBackground(new java.awt.Color(255, 255, 255));
        grupoBorda.add(bordaPadrao);
        bordaPadrao.setSelected(true);
        bordaPadrao.setText("Borda Padrão");
        jPanel5.add(bordaPadrao);

        radioCheddar.setBackground(new java.awt.Color(255, 255, 255));
        grupoBorda.add(radioCheddar);
        radioCheddar.setText("Borda Cheddar (4,50)");
        radioCheddar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCheddarActionPerformed(evt);
            }
        });
        jPanel5.add(radioCheddar);

        radioCatupiry.setBackground(new java.awt.Color(255, 255, 255));
        grupoBorda.add(radioCatupiry);
        radioCatupiry.setText("Borda Catupiry (3,00)");
        jPanel5.add(radioCatupiry);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pizzas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        botEditarPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/selecione.png"))); // NOI18N
        botEditarPizza.setText("Adicionar Observacao");
        botEditarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEditarPizzaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/conjunto-de-setas-de-sincronizacao.png"))); // NOI18N
        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botEditarPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botEditarPizza)
                .addGap(7, 7, 7)
                .addComponent(cmbPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Adicionais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel7.setLayout(new java.awt.GridLayout(6, 2));

        chkCebola.setBackground(new java.awt.Color(255, 255, 255));
        chkCebola.setText("Cebola (2,00)");
        jPanel7.add(chkCebola);

        chkMussarela.setBackground(new java.awt.Color(255, 255, 255));
        chkMussarela.setText("Mussarela (6,00)");
        jPanel7.add(chkMussarela);

        chkPalmito.setBackground(new java.awt.Color(255, 255, 255));
        chkPalmito.setText("Palmito (2,00)");
        jPanel7.add(chkPalmito);

        chkBacon.setBackground(new java.awt.Color(255, 255, 255));
        chkBacon.setText("Bacon (4,00)");
        jPanel7.add(chkBacon);

        chkAzeitona.setBackground(new java.awt.Color(255, 255, 255));
        chkAzeitona.setText("Azeitona (2,00)");
        jPanel7.add(chkAzeitona);

        chkOregano.setBackground(new java.awt.Color(255, 255, 255));
        chkOregano.setText("Orégano (1,00)");
        jPanel7.add(chkOregano);

        chkPresunto.setBackground(new java.awt.Color(255, 255, 255));
        chkPresunto.setText("Presunto (2,00)");
        jPanel7.add(chkPresunto);

        chkLombo.setBackground(new java.awt.Color(255, 255, 255));
        chkLombo.setText("Lombo Canadense (4,00)");
        jPanel7.add(chkLombo);

        chkAlho.setBackground(new java.awt.Color(255, 255, 255));
        chkAlho.setText("Alho Tostado (1,00)");
        jPanel7.add(chkAlho);

        chkAtum.setBackground(new java.awt.Color(255, 255, 255));
        chkAtum.setText("Atum (5,00)");
        jPanel7.add(chkAtum);

        chkOvo.setBackground(new java.awt.Color(255, 255, 255));
        chkOvo.setText("Ovo (2,00)");
        jPanel7.add(chkOvo);

        chkBarbecue.setBackground(new java.awt.Color(255, 255, 255));
        chkBarbecue.setText("Molho Barbecue (3,00)");
        jPanel7.add(chkBarbecue);

        chkMaionese.setBackground(new java.awt.Color(255, 255, 255));
        chkMaionese.setText("Maionese Caseira (2,00)");
        chkMaionese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMaioneseActionPerformed(evt);
            }
        });
        jPanel7.add(chkMaionese);

        botAdicionar.setBackground(new java.awt.Color(102, 255, 255));
        botAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/botao-adicionar.png"))); // NOI18N
        botAdicionar.setText("Adicionar no Carrinho");
        botAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdicionarActionPerformed(evt);
            }
        });

        botEncerrar.setBackground(java.awt.Color.orange);
        botEncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/cesta-de-compras.png"))); // NOI18N
        botEncerrar.setText("Encerrar Pedido");
        botEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEncerrarActionPerformed(evt);
            }
        });

        botSair.setBackground(new java.awt.Color(255, 0, 0));
        botSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/sair.png"))); // NOI18N
        botSair.setText("Sair");
        botSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Total");

        txtTotal.setEditable(false);
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel8.setText("Marchiori's Pizzaria");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/pizza.png"))); // NOI18N

        jTableCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pizza", "Tamanho", "Ingredientes", "Adicionais", "Observacao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCarrinho.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(jTableCarrinho);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/icone_pizza_maior.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jLabel8)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(52, 52, 52))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(botAdicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botEncerrar)
                                        .addGap(25, 25, 25)
                                        .addComponent(botSair, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(91, 91, 91)))))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(botAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botSair, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botEncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(62, 62, 62))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void radioCheddarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCheddarActionPerformed

    }//GEN-LAST:event_radioCheddarActionPerformed

    private void botPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesquisarActionPerformed
        cliSelecionado = gerIG.janelaPesqCliente();
        
        // Se selecionar um cliente, seta o nome dele como principal
        if (cliSelecionado != null) {
            txtNome.setText(cliSelecionado.getNome());
            esconderCampos();
            botAlterar.setVisible(false);
            txtNome.setEditable(false);
            botLimpar.setVisible(false);
            botAlterar.setVisible(false);
            botAlterar.setVisible(true);
            botAdicionarCliente1.setVisible(false);
        }
    }//GEN-LAST:event_botPesquisarActionPerformed

    private void botEditarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEditarPizzaActionPerformed
        Pizza obj = (Pizza) (cmbPizzas.getSelectedItem());
        gerIG.setObj(obj);
        gerIG.janelaCadPizza();
    }//GEN-LAST:event_botEditarPizzaActionPerformed

    private void botAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdicionarActionPerformed

        List<Adicional> adicional = new ArrayList();
        tamanho = (char) grupoTamanho.getSelection().getMnemonic();
        if (radioPequena.isSelected()) {
            subtotal += 5;
        } else if (radioMedia.isSelected()) {
            subtotal += 15;

        } else if (radioGrande.isSelected()) {
            subtotal += 20;
        }

        if (chkMaionese.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(1);
            adicional.add(adc);
            subtotal += adc.getPreco();
        }

        if (chkBarbecue.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(2);
            adicional.add(adc);
            subtotal += 3;
        }

        if (radioCheddar.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(4);
            adicional.add(adc);
            subtotal += 4.5;
        }

        if (radioCatupiry.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(3);
            adicional.add(adc);
            subtotal += 3;
        }

        if (chkCebola.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(5);
            adicional.add(adc);
            subtotal += 2;
        }

        if (chkMussarela.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(6);
            adicional.add(adc);
            subtotal += 6;
        }

        if (chkPalmito.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(7);
            adicional.add(adc);
            subtotal += 2;
        }

        if (chkBacon.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(8);
            adicional.add(adc);
            subtotal += 4;
        }

        if (chkAzeitona.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(9);
            adicional.add(adc);
            subtotal += 2;
        }

        if (chkOregano.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(10);
            adicional.add(adc);
            subtotal += 1;
        }
        if (chkPresunto.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(11);
            adicional.add(adc);
            subtotal += 2;
        }
        if (chkLombo.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(12);
            adicional.add(adc);
            subtotal += 4;
        }
        if (chkAlho.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(13);
            adicional.add(adc);
            subtotal += 1;
        }

        if (chkAtum.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(14);
            adicional.add(adc);
            subtotal += 5;
        }

        if (chkOvo.isSelected()) {
            Adicional adc = gerIG.getGerDominio().getAdicional(15);
            adicional.add(adc);
            subtotal += 2;
        }

        // PEGAR OS CAMPOS
        Pizza pizza = (Pizza) cmbPizzas.getSelectedItem();

        System.out.println("valor pizza: " + pizza.getValorPizza());
        System.out.println("valor subtotal: " + subtotal);

        //Somando o valor da pizza com os adicionais
        subtotal += pizza.getValorPizza();

        //Arredondando o valor
        subtotal = Math.ceil(subtotal);

        //Convertendo o valor em double para String
        String total = String.valueOf(subtotal);

        //Setando no campo de subtotal na interface gráfica
        txtTotal.setText(total);
        adicionarTabela(pizza, tamanho, adicional);
    }//GEN-LAST:event_botAdicionarActionPerformed

    private void adicionarTabela(Pizza pizza, char tamanho, List adicional) {

        // ADICIONAR LINHA NA TABELA        
        ((DefaultTableModel) jTableCarrinho.getModel()).addRow(new Object[4]);

        int linha = jTableCarrinho.getRowCount() - 1;
        int coluna = 0;
        jTableCarrinho.setValueAt(pizza, linha, coluna++);
        jTableCarrinho.setValueAt(tamanho, linha, coluna++);
        jTableCarrinho.setValueAt(pizza.getIngrediente(), linha, coluna++);
        jTableCarrinho.setValueAt(adicional, linha, coluna++);
        jTableCarrinho.setValueAt(gerIG.getObservacao(), linha, coluna++);

    }
    private void botEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEncerrarActionPerformed

        if (cliSelecionado != null) {

            int idPedido;

            if ((JOptionPane.showConfirmDialog(null, "Deseja que seja entregue seu pedido? (Adicional de 2,00)", "Entrega Pedido", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0)) {
                entregar = 1;
                subtotal += 2;
                String total = String.valueOf(subtotal);
                txtTotal.setText(total);

            }

            idPedido = gerIG.getGerDominio().inserirPedido(cliSelecionado, entregar, subtotal, jTableCarrinho, gerIG.getObservacao());
            JOptionPane.showMessageDialog(this, "Pedido " + idPedido + " inserido com sucesso.");
            JOptionPane.showMessageDialog(this, "Logo mais sua pizza estará prontinha para você! ");
            limparPedido();
            subtotal = 0;

        } else {
            JOptionPane.showMessageDialog(this, "Selecione um cliente.");
        }
    }//GEN-LAST:event_botEncerrarActionPerformed

    private void botSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSairActionPerformed
        gerIG.encerrarPrograma(this);
    }//GEN-LAST:event_botSairActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        gerIG.carregarCombo(cmbPizzas, Pizza.class);
        botAlterar.setVisible(false);
    }//GEN-LAST:event_formComponentShown

    private void botAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAlterarActionPerformed
        if (cliSelecionado != null) {
            mostrarCampos();
            botPesquisar.setVisible(false);
            botAdicionarCliente1.setVisible(true);
            botAlterar.setVisible(false);
            botLimpar.setVisible(true);
            txtBairro.setText(cliSelecionado.getBairro());
            txtRua.setText(cliSelecionado.getRua());
            String numero_convertido = String.valueOf(cliSelecionado.getNumero());
            txtNumero.setText(numero_convertido);
            String telefone_convertido = String.valueOf(cliSelecionado.getTelefone());
            txtTelefone.setText(telefone_convertido);
        }      
    }//GEN-LAST:event_botAlterarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gerIG.carregarCombo(cmbPizzas, Pizza.class);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chkMaioneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMaioneseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMaioneseActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void botLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimparActionPerformed
        txtNome.setText("");
        txtBairro.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtTelefone.setText("");
    }//GEN-LAST:event_botLimparActionPerformed

    private void botAdicionarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdicionarCliente1ActionPerformed
        String nome = txtNome.getText();
        String numero = txtNumero.getText();
        String bairro = txtBairro.getText();
        String rua = txtRua.getText();
        String telefone = txtTelefone.getText();

        if (validarCampos()) {
            // INSERIR NO BANCO
            try {
                telefone = telefone.replace("(", "");
                telefone = telefone.replace(")", "");
                telefone = telefone.replace("-", "");
                int num = Integer.parseInt(numero);

                if (cliSelecionado == null) {

                    long tel = Long.parseLong(telefone);
                    int id = gerIG.getGerDominio().inserirCliente(nome, num, bairro, rua, tel);
                    JOptionPane.showMessageDialog(this, "Cliente " + id + " " + "( " + nome + " )" + " inserido com sucesso.", "Inserir Cliente", JOptionPane.INFORMATION_MESSAGE);
                    esconderCampos();
                    botAlterar.setVisible(true);
                    txtNome.setText(nome);
                    txtNome.setEditable(false);
                    botLimpar.setVisible(false);
                    cliSelecionado = gerIG.getGerDominio().getCliente(id);
                    botAdicionarCliente1.setVisible(false);
                } else {
                    // ALTERAR
                    long tel = Long.parseLong(telefone);
                    gerIG.getGerDominio().alterarCliente(cliSelecionado, nome, num, bairro, rua, tel);
                    int id = cliSelecionado.getIdCliente();
                    JOptionPane.showMessageDialog(this, "Cliente " + id + " alterado com sucesso.", "Inserir Cliente", JOptionPane.INFORMATION_MESSAGE  );  
                    limparPedido();
                }

            } catch (HibernateException ex) {
                JOptionPane.showMessageDialog(this, ex, "ERRO Cliente", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_botAdicionarCliente1ActionPerformed

    // Funcao para esconder os campos do cliente
    private void esconderCampos() {
        txtNumero.setVisible(false);
        lblNumero.setVisible(false);
        txtBairro.setVisible(false);
        lblBairro.setVisible(false);
        txtRua.setVisible(false);
        lblRua.setVisible(false);
        txtTelefone.setVisible(false);
        lblTelefone.setVisible(false);
    }

    // Funcao para mostrar os campos do cliente
    private void mostrarCampos() {
        txtNumero.setVisible(true);
        botAlterar.setVisible(true);
        botPesquisar.setVisible(true);
        botAlterar.setVisible(true);
        lblNumero.setVisible(true);
        txtBairro.setVisible(true);
        lblBairro.setVisible(true);
        txtRua.setVisible(true);
        lblRua.setVisible(true);
        txtTelefone.setVisible(true);
        lblTelefone.setVisible(true);
        txtNome.setEditable(true);
        botLimpar.setVisible(true);

    }

    // Funcao para validar os campos antes de adicionar um cliente
    private boolean validarCampos() {

        String msgErro = "";

        lblNome.setForeground(Color.black);
        lblBairro.setForeground(Color.black);
        lblNumero.setForeground(Color.black);
        lblRua.setForeground(Color.black);
        lblTelefone.setForeground(Color.black);

        if (txtNome.getText().equals("")) {
            msgErro = msgErro + "Digite seu nome.\n";
            lblNome.setForeground(Color.red);
        }
        if (txtBairro.getText().equals("")) {
            msgErro = msgErro + "Digite seu bairro.\n";
            lblBairro.setForeground(Color.red);
        }

        if (txtRua.getText().equals("")) {
            msgErro = msgErro + "Digite sua rua.\n";
            lblRua.setForeground(Color.red);
        }

        if (txtNumero.getText().equals("")) {
            msgErro = msgErro + "Número inválido.\n";
            lblNumero.setForeground(Color.red);
        }

        try {
            String telefone = txtTelefone.getText();
            telefone = telefone.replace("(", "");
            telefone = telefone.replace(")", "");
            telefone = telefone.replace("-", "");
            long num = Long.parseLong(telefone);
        } catch (NumberFormatException erro) {
            msgErro = msgErro + "Telefone inválido.\n";
            lblTelefone.setForeground(Color.red);
        }
        // COLOCAR VALIDAÇÃO DOS OUTROS CAMPOS
        if (msgErro.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, msgErro, "ERRO Cliente", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    // Funcao para limpar o pedido
    private void limparPedido() {

        cliSelecionado = null;
        mostrarCampos();
        txtNome.setText("");
        txtBairro.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtTelefone.setText("");
        bordaPadrao.setSelected(true);
        chkCebola.setSelected(false);
        chkMussarela.setSelected(false);
        chkPalmito.setSelected(false);
        chkBacon.setSelected(false);
        chkAzeitona.setSelected(false);
        chkOregano.setSelected(false);
        chkPresunto.setSelected(false);
        chkLombo.setSelected(false);
        chkAlho.setSelected(false);
        chkAtum.setSelected(false);
        chkOvo.setSelected(false);
        chkBarbecue.setSelected(false);
        chkMaionese.setSelected(false);
        txtTotal.setText("");

        // ZERAR a TABELA
        ((DefaultTableModel) jTableCarrinho.getModel()).setRowCount(0);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bordaPadrao;
    private javax.swing.JButton botAdicionar;
    private javax.swing.JButton botAdicionarCliente1;
    private javax.swing.JButton botAlterar;
    private javax.swing.JButton botEditarPizza;
    private javax.swing.JButton botEncerrar;
    private javax.swing.JButton botLimpar;
    private javax.swing.JButton botPesquisar;
    private javax.swing.JButton botSair;
    private javax.swing.JCheckBox chkAlho;
    private javax.swing.JCheckBox chkAtum;
    private javax.swing.JCheckBox chkAzeitona;
    private javax.swing.JCheckBox chkBacon;
    private javax.swing.JCheckBox chkBarbecue;
    private javax.swing.JCheckBox chkCebola;
    private javax.swing.JCheckBox chkLombo;
    private javax.swing.JCheckBox chkMaionese;
    private javax.swing.JCheckBox chkMussarela;
    private javax.swing.JCheckBox chkOregano;
    private javax.swing.JCheckBox chkOvo;
    private javax.swing.JCheckBox chkPalmito;
    private javax.swing.JCheckBox chkPresunto;
    private javax.swing.JComboBox<String> cmbPizzas;
    private javax.swing.ButtonGroup grupoBorda;
    private javax.swing.ButtonGroup grupoTamanho;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableCarrinho;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JRadioButton radioCatupiry;
    private javax.swing.JRadioButton radioCheddar;
    private javax.swing.JRadioButton radioGrande;
    private javax.swing.JRadioButton radioMedia;
    private javax.swing.JRadioButton radioPequena;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
