/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Janelas;

import Controladora.Interface_Grafica;

/**
 *
 * @author luiz.marchiori
 */
public class janelaPadrao extends javax.swing.JFrame {

    private Interface_Grafica gerIG;

    public janelaPadrao(Interface_Grafica gerIG) {
        this.gerIG = gerIG;
        initComponents();
        esconderBotoes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBorda = new javax.swing.ButtonGroup();
        grupoTamanho = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtNumero = new javax.swing.JFormattedTextField();
        txtRua = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        botCriar = new javax.swing.JButton();
        botPesquisar = new javax.swing.JButton();
        botAdicionarCliente = new javax.swing.JButton();
        botLimpar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        radioPequena = new javax.swing.JRadioButton();
        radioMedia = new javax.swing.JRadioButton();
        radioGrande = new javax.swing.JRadioButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        chkEntregar = new javax.swing.JCheckBox();
        chkMaionese = new javax.swing.JCheckBox();
        chkBarbecue = new javax.swing.JCheckBox();
        radioCatupiry = new javax.swing.JRadioButton();
        radioCheddar = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        botAdicionarPizza = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        chkCebola = new javax.swing.JCheckBox();
        chkMussarela = new javax.swing.JCheckBox();
        chkPalmito = new javax.swing.JCheckBox();
        chkBacon = new javax.swing.JCheckBox();
        chkAzeitona = new javax.swing.JCheckBox();
        chkOregano = new javax.swing.JCheckBox();
        chkPresunto = new javax.swing.JCheckBox();
        chkLombo = new javax.swing.JCheckBox();
        chkAlho = new javax.swing.JCheckBox();
        chkAtum = new javax.swing.JCheckBox();
        chkOvo = new javax.swing.JCheckBox();
        botAdicionar = new javax.swing.JButton();
        botEncerrar = new javax.swing.JButton();
        botSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criar Pedido");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nome");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 114, -1, -1));

        lblBairro.setText("Bairro");
        jPanel3.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 145, -1, -1));

        lblRua.setText("Rua");
        jPanel3.add(lblRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 176, -1, -1));

        lblNumero.setText("Número");
        jPanel3.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 207, -1, -1));

        lblTelefone.setText("Telefone");
        jPanel3.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 238, -1, -1));

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 235, 228, -1));

        txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jPanel3.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 204, 228, -1));
        jPanel3.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 173, 228, -1));
        jPanel3.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 142, 228, -1));
        jPanel3.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 111, 228, -1));

        botCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/botao-adicionar.png"))); // NOI18N
        botCriar.setText("Adicionar");
        botCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCriarActionPerformed(evt);
            }
        });
        jPanel3.add(botCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 52, 130, -1));

        botPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/lupa.png"))); // NOI18N
        botPesquisar.setText("Pesquisar");
        botPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesquisarActionPerformed(evt);
            }
        });
        jPanel3.add(botPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 52, 136, -1));

        botAdicionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/verifica.png"))); // NOI18N
        jPanel3.add(botAdicionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, 45));

        botLimpar.setText("Cancelar");
        botLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimparActionPerformed(evt);
            }
        });
        jPanel3.add(botLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 45));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tamanho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        radioPequena.setBackground(new java.awt.Color(255, 255, 255));
        grupoTamanho.add(radioPequena);
        radioPequena.setText("Pequena");

        radioMedia.setBackground(new java.awt.Color(255, 255, 255));
        grupoTamanho.add(radioMedia);
        radioMedia.setText("Média");

        radioGrande.setBackground(new java.awt.Color(255, 255, 255));
        grupoTamanho.add(radioGrande);
        radioGrande.setText("Grande");

        jTextField5.setEditable(false);
        jTextField5.setText("30,00");

        jTextField6.setEditable(false);
        jTextField6.setText("42,00");

        jTextField7.setEditable(false);
        jTextField7.setText("53,00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioPequena)
                    .addComponent(radioMedia)
                    .addComponent(radioGrande))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jTextField5)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPequena)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMedia)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioGrande)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        chkEntregar.setBackground(new java.awt.Color(255, 255, 255));
        chkEntregar.setText("Entregar (2,00)");
        jPanel5.add(chkEntregar);

        chkMaionese.setBackground(new java.awt.Color(255, 255, 255));
        chkMaionese.setText("Maionese Caseira (2,00)");
        jPanel5.add(chkMaionese);

        chkBarbecue.setBackground(new java.awt.Color(255, 255, 255));
        chkBarbecue.setText("Molho Barbecue (3,00)");
        jPanel5.add(chkBarbecue);

        radioCatupiry.setBackground(new java.awt.Color(255, 255, 255));
        grupoBorda.add(radioCatupiry);
        radioCatupiry.setText("Borda Catupiry (3,00)");
        jPanel5.add(radioCatupiry);

        radioCheddar.setBackground(new java.awt.Color(255, 255, 255));
        grupoBorda.add(radioCheddar);
        radioCheddar.setText("Borda Cheddar (4,50)");
        radioCheddar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCheddarActionPerformed(evt);
            }
        });
        jPanel5.add(radioCheddar);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pizzas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        botAdicionarPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/botao-adicionar.png"))); // NOI18N
        botAdicionarPizza.setText("Adicionar nova pizza");
        botAdicionarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdicionarPizzaActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 208, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botAdicionarPizza)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botAdicionarPizza))
                .addGap(35, 35, 35))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Adicionais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel7.setLayout(new java.awt.GridLayout(6, 2));

        chkCebola.setBackground(new java.awt.Color(255, 255, 255));
        chkCebola.setText("Cebola (2,00)");
        jPanel7.add(chkCebola);

        chkMussarela.setBackground(new java.awt.Color(255, 255, 255));
        chkMussarela.setText("Mussarela (6,00)");
        jPanel7.add(chkMussarela);

        chkPalmito.setBackground(new java.awt.Color(255, 255, 255));
        chkPalmito.setText("Palmito (2,00)");
        jPanel7.add(chkPalmito);

        chkBacon.setBackground(new java.awt.Color(255, 255, 255));
        chkBacon.setText("Bacon (4,00)");
        jPanel7.add(chkBacon);

        chkAzeitona.setBackground(new java.awt.Color(255, 255, 255));
        chkAzeitona.setText("Azeitona (2,00)");
        jPanel7.add(chkAzeitona);

        chkOregano.setBackground(new java.awt.Color(255, 255, 255));
        chkOregano.setText("Orégano (1,00)");
        jPanel7.add(chkOregano);

        chkPresunto.setBackground(new java.awt.Color(255, 255, 255));
        chkPresunto.setText("Presunto (2,00)");
        jPanel7.add(chkPresunto);

        chkLombo.setBackground(new java.awt.Color(255, 255, 255));
        chkLombo.setText("Lombo canadense (4,00)");
        jPanel7.add(chkLombo);

        chkAlho.setBackground(new java.awt.Color(255, 255, 255));
        chkAlho.setText("Alho Tostado (1,00)");
        jPanel7.add(chkAlho);

        chkAtum.setBackground(new java.awt.Color(255, 255, 255));
        chkAtum.setText("Atum (5,00)");
        jPanel7.add(chkAtum);

        chkOvo.setBackground(new java.awt.Color(255, 255, 255));
        chkOvo.setText("Ovo (2,00)");
        jPanel7.add(chkOvo);

        botAdicionar.setBackground(new java.awt.Color(102, 255, 255));
        botAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/botao-adicionar.png"))); // NOI18N
        botAdicionar.setText("Adicionar no Carrinho");
        botAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdicionarActionPerformed(evt);
            }
        });

        botEncerrar.setBackground(java.awt.Color.orange);
        botEncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/cesta-de-compras.png"))); // NOI18N
        botEncerrar.setText("Encerrar Pedido");
        botEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEncerrarActionPerformed(evt);
            }
        });

        botSair.setBackground(new java.awt.Color(255, 0, 0));
        botSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/sair.png"))); // NOI18N
        botSair.setText("Sair");
        botSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Total");

        txtTotal.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel8.setText("Marchiori's Pizzaria");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/pizza.png"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Pizza", "Ingredientes", "Adicionais", "Entregar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intergraf/imagens/icone_pizza_maior.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jLabel8)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(52, 52, 52))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(botAdicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botEncerrar)
                                        .addGap(25, 25, 25)
                                        .addComponent(botSair, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(91, 91, 91)))))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botSair, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botEncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(62, 62, 62))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarBotoes() {
        lblBairro.setVisible(true);
        txtBairro.setVisible(true);
        lblNumero.setVisible(true);
        txtNumero.setVisible(true);
        lblRua.setVisible(true);
        txtRua.setVisible(true);
        lblTelefone.setVisible(true);
        txtTelefone.setVisible(true);
        botAdicionarCliente.setVisible(true);
        botLimpar.setVisible(true);

    }

    private void esconderBotoes() {
        lblBairro.setVisible(false);
        txtBairro.setVisible(false);
        lblNumero.setVisible(false);
        txtNumero.setVisible(false);
        lblRua.setVisible(false);
        txtRua.setVisible(false);
        lblTelefone.setVisible(false);
        txtTelefone.setVisible(false);
        botAdicionarCliente.setVisible(false);
        botLimpar.setVisible(false);

    }
    private void radioCheddarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCheddarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCheddarActionPerformed

    private void botCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCriarActionPerformed
        mostrarBotoes();
        botPesquisar.setVisible(false);
    }//GEN-LAST:event_botCriarActionPerformed

    private void botPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesquisarActionPerformed

    }//GEN-LAST:event_botPesquisarActionPerformed

    private void botAdicionarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdicionarPizzaActionPerformed
        gerIG.janelaCadPizza();
    }//GEN-LAST:event_botAdicionarPizzaActionPerformed

    private void botAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botAdicionarActionPerformed

    private void botEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEncerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botEncerrarActionPerformed

    private void botSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSairActionPerformed
        gerIG.encerrarPrograma(this);
    }//GEN-LAST:event_botSairActionPerformed

    private void botLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimparActionPerformed
        txtNome.setText("");
        txtBairro.setText("");
        txtNumero.setText("");
        txtRua.setText("");
        txtTelefone.setText("");
        esconderBotoes();
        botPesquisar.setVisible(true);
    }//GEN-LAST:event_botLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAdicionar;
    private javax.swing.JButton botAdicionarCliente;
    private javax.swing.JButton botAdicionarPizza;
    private javax.swing.JButton botCriar;
    private javax.swing.JButton botEncerrar;
    private javax.swing.JButton botLimpar;
    private javax.swing.JButton botPesquisar;
    private javax.swing.JButton botSair;
    private javax.swing.JCheckBox chkAlho;
    private javax.swing.JCheckBox chkAtum;
    private javax.swing.JCheckBox chkAzeitona;
    private javax.swing.JCheckBox chkBacon;
    private javax.swing.JCheckBox chkBarbecue;
    private javax.swing.JCheckBox chkCebola;
    private javax.swing.JCheckBox chkEntregar;
    private javax.swing.JCheckBox chkLombo;
    private javax.swing.JCheckBox chkMaionese;
    private javax.swing.JCheckBox chkMussarela;
    private javax.swing.JCheckBox chkOregano;
    private javax.swing.JCheckBox chkOvo;
    private javax.swing.JCheckBox chkPalmito;
    private javax.swing.JCheckBox chkPresunto;
    private javax.swing.ButtonGroup grupoBorda;
    private javax.swing.ButtonGroup grupoTamanho;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JRadioButton radioCatupiry;
    private javax.swing.JRadioButton radioCheddar;
    private javax.swing.JRadioButton radioGrande;
    private javax.swing.JRadioButton radioMedia;
    private javax.swing.JRadioButton radioPequena;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
